import { describe, it, expect } from 'vitest';
import { buildGraph } from '../graph';
import { generateSketch } from '../emitter';
import type { CompoundTypeDefinition, DiagramNode, DiagramConnection } from '../../types/diagram';

function makeSensor(overrides: Partial<DiagramNode> = {}): DiagramNode {
  return {
    id: 'sensor-1',
    type: 'sensor-analog',
    label: 'Sensor 1',
    x: 0,
    y: 0,
    arduinoPort: 'A0',
    ...overrides,
  };
}

function makeMotor(overrides: Partial<DiagramNode> = {}): DiagramNode {
  return {
    id: 'motor-left',
    type: 'servo-cr',
    label: 'Left Wheel',
    x: 0,
    y: 0,
    servoPin: '9',
    ...overrides,
  };
}

function makeRightMotor(overrides: Partial<DiagramNode> = {}): DiagramNode {
  return {
    id: 'motor-right',
    type: 'servo-cr',
    label: 'Right Wheel',
    x: 0,
    y: 0,
    servoPin: '10',
    ...overrides,
  };
}

function conn(c: Omit<DiagramConnection, 'transferMode' | 'transferPoints'> & Partial<Pick<DiagramConnection, 'transferMode' | 'transferPoints'>>): DiagramConnection {
  return {
    transferMode: 'linear',
    transferPoints: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
    ...c,
  };
}

describe('generateSketch', () => {
  it('generates a minimal sketch with float signals', () => {
    const nodes: DiagramNode[] = [makeSensor(), makeMotor(), makeRightMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'motor-left', weight: 0.8 }),
      conn({ id: 'c2', from: 'sensor-1', to: 'motor-right', weight: 0.8 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('Auto-generated by BraitenBot GUI');
    // Analog sensor normalized to 0–100, using label-based names
    expect(code).toContain('analogRead(SENSOR_Sensor_1) * (100.0 / 1023.0)');
    expect(code).toContain('float sig_Sensor_1');
    // Servo.h is included, and wheels are declared as Servo objects.
    expect(code).toContain('#include <Servo.h>');
    expect(code).toContain('Servo servo_Left_Wheel;');
    expect(code).toContain('Servo servo_Right_Wheel;');
    // drive() helper present and called at the end of loop().
    expect(code).toContain('void drive(float left, float right)');
    expect(code).toContain('drive(input_Left_Wheel, input_Right_Wheel)');
    expect(code).toContain('0.8000');
    expect(code).toContain('unsigned long _loopStart = millis();');
    expect(code).toContain('if (_elapsed < 20) delay(20 - _elapsed);');
  });

  it('inverts an analog sensor read when invert is set', () => {
    const nodes: DiagramNode[] = [
      makeSensor({ invert: true }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'motor-left', weight: 1 }),
      conn({ id: 'c2', from: 'sensor-1', to: 'motor-right', weight: 1 }),
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    expect(code).toContain('100.0 - (analogRead(SENSOR_Sensor_1) * (100.0 / 1023.0))');
  });

  it('inverts the right servo inside the drive() helper', () => {
    const nodes: DiagramNode[] = [makeSensor(), makeMotor(), makeRightMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'motor-left', weight: 1 }),
      conn({ id: 'c2', from: 'sensor-1', to: 'motor-right', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // Left wheel: +left * 5.
    // Right wheel: -right * 5 (inverted mounting).
    expect(code).toMatch(/servo_Left_Wheel\.writeMicroseconds\(1500 \+ \(int\)\(left\s+\* 5\.0\)\)/);
    expect(code).toMatch(/servo_Right_Wheel\.writeMicroseconds\(1500 - \(int\)\(right \* 5\.0\)\)/);
    // Old H-bridge style output must not appear.
    expect(code).not.toContain('analogWrite(MOTOR_');
    expect(code).not.toContain('fabs(');
  });

  it('passes negative weights straight through to drive()', () => {
    const nodes: DiagramNode[] = [makeSensor(), makeMotor(), makeRightMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'motor-left', weight: -0.5 }),
      conn({ id: 'c2', from: 'sensor-1', to: 'motor-right', weight: -0.5 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // Motor nodes only aggregate inputs; the sign-handling now lives in drive().
    expect(code).toContain('-0.5000');
    expect(code).toContain('float input_Left_Wheel = 0.0;');
    expect(code).toContain('input_Left_Wheel += sig_Sensor_1 * -0.5000;');
    expect(code).not.toContain('if (input_Left_Wheel >= 0)');
    // drive() clamps to [-100, 100] before writing microseconds.
    expect(code).toContain('constrain(left,  -100.0, 100.0)');
    expect(code).toContain('constrain(right, -100.0, 100.0)');
  });

  it('generates threshold node with float comparison', () => {
    const thresh: DiagramNode = {
      id: 'thresh-1',
      type: 'compute-threshold',
      label: 'Threshold',
      x: 0,
      y: 0,
      threshold: 70,
    };
    const nodes: DiagramNode[] = [makeSensor(), thresh, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'thresh-1', weight: 1 }),
      conn({ id: 'c2', from: 'thresh-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('> 70.0000');
    expect(code).toContain('? 100.0 : 0.0');
    expect(code).toContain('float sig_Threshold');
  });

  it('generates multiply node as a product of weighted edges', () => {
    const mult: DiagramNode = {
      id: 'mult-1',
      type: 'compute-multiply',
      label: 'Gate',
      x: 0,
      y: 0,
    };
    const s2 = makeSensor({ id: 'sensor-2', label: 'Sensor 2', arduinoPort: 'A1' });
    const nodes: DiagramNode[] = [makeSensor(), s2, mult, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'mult-1', weight: 1 }),
      conn({ id: 'c2', from: 'sensor-2', to: 'mult-1', weight: 1 }),
      conn({ id: 'c3', from: 'mult-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('float input_Gate = 1.0');
    expect(code).toContain('input_Gate *= (sig_Sensor_1');
    expect(code).toContain('input_Gate *= (sig_Sensor_2');
    expect(code).toContain('float sig_Gate = input_Gate');
  });

  it('generates delay node as a float ring buffer', () => {
    const delayNode: DiagramNode = {
      id: 'delay-1',
      type: 'compute-delay',
      label: 'Delay',
      x: 0,
      y: 0,
      delayMs: 200,
    };
    const nodes: DiagramNode[] = [makeSensor(), delayNode, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'delay-1', weight: 1 }),
      conn({ id: 'c2', from: 'delay-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('BUF_SIZE = 10');
    expect(code).toContain('static float sig_Delay_buf');
    expect(code).toContain('float sig_Delay =');
    // The delay read happens at the node's normal position; the input
    // aggregation + buffer write are deferred to the end of loop() so the
    // delay can break feedback cycles.
    expect(code).toContain('sig_Delay_buf[sig_Delay_idx] = input_Delay');
    // The read must appear before the write in the emitted loop.
    const readPos = code.indexOf('float sig_Delay =');
    const writePos = code.indexOf('sig_Delay_buf[sig_Delay_idx] = input_Delay');
    expect(readPos).toBeGreaterThan(-1);
    expect(writePos).toBeGreaterThan(readPos);
  });

  it('allows feedback cycles when broken by a delay node', () => {
    // A node feeding back into itself through a delay forms a recurrent
    // loop. buildGraph must accept this (no CycleError), and the emitted
    // sketch must still reference the back-edge in the delay's input.
    const delayNode: DiagramNode = {
      id: 'delay-1',
      type: 'compute-delay',
      label: 'Delay',
      x: 0,
      y: 0,
      delayMs: 40,
    };
    const sumNode: DiagramNode = {
      id: 'sum-1',
      type: 'compute-summation',
      label: 'Sum',
      x: 0,
      y: 0,
    };
    const nodes: DiagramNode[] = [makeSensor(), sumNode, delayNode, makeMotor(), makeRightMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'sum-1', weight: 1 }),
      // Recurrent self-loop: Sum -> Delay -> Sum
      conn({ id: 'c2', from: 'sum-1', to: 'delay-1', weight: 0.9 }),
      conn({ id: 'c3', from: 'delay-1', to: 'sum-1', weight: 0.5 }),
      conn({ id: 'c4', from: 'sum-1', to: 'motor-left', weight: 1 }),
      conn({ id: 'c5', from: 'sum-1', to: 'motor-right', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // The cycle is accepted (no throw) and the delay's input aggregation
    // references the back-edge from Sum.
    expect(code).toContain('input_Delay');
    expect(code).toContain('sig_Sum');
  });

  it('generates digital output as pinMode + digitalWrite', () => {
    const ledNode: DiagramNode = {
      id: 'out-1',
      type: 'digital-out',
      label: 'LED',
      x: 0,
      y: 0,
      servoPin: '13',
      threshold: 60,
    };
    const nodes: DiagramNode[] = [makeSensor(), ledNode];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'out-1', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('const int OUTPUT_LED_PIN = 13;');
    expect(code).toContain('pinMode(OUTPUT_LED_PIN, OUTPUT)');
    expect(code).toContain('digitalWrite(OUTPUT_LED_PIN, input_LED > 60.0000 ? HIGH : LOW)');
    // No servo-related output when only digital-out actuators are present.
    expect(code).not.toContain('#include <Servo.h>');
    expect(code).not.toContain('Servo servo_LED');
  });

  it('generates digital sensor as float', () => {
    const nodes: DiagramNode[] = [
      makeSensor({ id: 'dig-1', type: 'sensor-digital', label: 'Digital Sensor', arduinoPort: '2' }),
      makeMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'dig-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('digitalRead(SENSOR_Digital_Sensor) * 100.0');
    expect(code).toContain('float sig_Digital_Sensor');
    expect(code).toContain('pinMode(SENSOR_Digital_Sensor, INPUT)');
  });

  it('inverts digital sensor reads when INPUT_PULLUP is enabled', () => {
    const nodes: DiagramNode[] = [
      makeSensor({
        id: 'dig-1',
        type: 'sensor-digital',
        label: 'Bumper',
        arduinoPort: '2',
        pullup: true,
      }),
      makeMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'dig-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('pinMode(SENSOR_Bumper, INPUT_PULLUP)');
    expect(code).toContain('(1 - digitalRead(SENSOR_Bumper)) * 100.0');
    expect(code).not.toMatch(/=\s*digitalRead\(SENSOR_Bumper\)\s*\*/);
  });

  it('emits a TCS34725 driver and one variable per channel for color sensors', () => {
    const nodes: DiagramNode[] = [
      makeSensor({
        id: 'color-1',
        type: 'sensor-color',
        label: 'Front Color',
        arduinoPort: undefined,
      }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      // Two edges from the same sensor but different output ports.
      { ...conn({ id: 'c1', from: 'color-1', to: 'motor-left', weight: 1 }), fromPort: 'red' },
      { ...conn({ id: 'c2', from: 'color-1', to: 'motor-right', weight: 0.5 }), fromPort: 'clear' },
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // Driver pulled in alongside Wire.h plumbing.
    expect(code).toContain('#include <Wire.h>');
    expect(code).toContain('Wire.begin()');
    expect(code).toContain('TCS34725_ADDR = 0x29');
    expect(code).toContain('struct TCS34725Sample { uint16_t c, r, g, b; };');
    expect(code).toContain('TCS34725Sample tcs34725_read_all()');
    expect(code).toContain('void tcs34725_begin(uint8_t gain)');
    // setup() initializes the chip with the default 16x gain (CONTROL 0x02).
    expect(code).toContain('tcs34725_begin(0x02);');
    // Single bulk read per loop, then four derived channel variables, each
    // normalized against the ADC's real full-scale count (not 65535).
    expect(code).toContain('const float TCS34725_FULL_SCALE = 44032.0;');
    expect(code).toContain('TCS34725Sample sample_Front_Color = tcs34725_read_all();');
    expect(code).toContain('float sig_Front_Color_clear = sample_Front_Color.c * (100.0 / TCS34725_FULL_SCALE);');
    expect(code).toContain('float sig_Front_Color_red   = sample_Front_Color.r * (100.0 / TCS34725_FULL_SCALE);');
    expect(code).toContain('float sig_Front_Color_green = sample_Front_Color.g * (100.0 / TCS34725_FULL_SCALE);');
    expect(code).toContain('float sig_Front_Color_blue  = sample_Front_Color.b * (100.0 / TCS34725_FULL_SCALE);');
    // Edges resolve to the port-specific variable, not a single sig_Front_Color.
    expect(code).toContain('input_Left_Wheel += sig_Front_Color_red * 1.0000;');
    expect(code).toContain('input_Right_Wheel += sig_Front_Color_clear * 0.5000;');
    // No bare `sig_Front_Color` without a port suffix — every reference must
    // go through one of the four channel-suffixed variables.
    expect(code).not.toMatch(/sig_Front_Color[^_a-zA-Z0-9]/);
  });

  it('brings up multiple VL53L4CD ToF sensors one at a time with unique addresses', () => {
    const nodes: DiagramNode[] = [
      makeSensor({ id: 'tof-1', type: 'sensor-tof', label: 'Left ToF', arduinoPort: undefined, xshutPin: '4', maxDistanceMm: 800 }),
      makeSensor({ id: 'tof-2', type: 'sensor-tof', label: 'Right ToF', arduinoPort: undefined, xshutPin: '5' }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'tof-1', to: 'motor-left', weight: 1 }),
      conn({ id: 'c2', from: 'tof-2', to: 'motor-right', weight: 1 }),
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    // Library include + per-sensor objects constructed with their XSHUT pins.
    expect(code).toContain('#include <vl53l4cd_class.h>');
    expect(code).toContain('const int XSHUT_Left_ToF = 4;');
    expect(code).toContain('const int XSHUT_Right_ToF = 5;');
    expect(code).toContain('VL53L4CD tof_Left_ToF(&Wire, XSHUT_Left_ToF);');
    expect(code).toContain('VL53L4CD tof_Right_ToF(&Wire, XSHUT_Right_ToF);');

    // The address trick: begin() ALL sensors (hold in reset) before any
    // InitSensor(), then readdress each off the shared default 0x52.
    const beginLeft = code.indexOf('tof_Left_ToF.begin();');
    const beginRight = code.indexOf('tof_Right_ToF.begin();');
    const initLeft = code.indexOf('tof_Left_ToF.InitSensor(0x54);');
    const initRight = code.indexOf('tof_Right_ToF.InitSensor(0x56);');
    expect(beginLeft).toBeGreaterThan(-1);
    expect(beginRight).toBeGreaterThan(-1);
    expect(initLeft).toBeGreaterThan(-1);
    expect(initRight).toBeGreaterThan(-1);
    // Both begins precede both inits.
    expect(Math.max(beginLeft, beginRight)).toBeLessThan(Math.min(initLeft, initRight));
    expect(code).toContain('tof_Left_ToF.VL53L4CD_StartRanging();');

    // Non-blocking read holds the last valid distance, mapped near = high
    // against the configured 800 mm full-scale.
    expect(code).toContain('static float dist_Left_ToF = 800.0;');
    // Status 0/1/2 use the measured distance; 3 (too close) → 0 mm; 4-7
    // (wraparound/fault) → max, so robot logic never sees a faulty distance.
    expect(code).toContain('if (status_Left_ToF <= 2) dist_Left_ToF = res_Left_ToF.distance_mm;');
    expect(code).toContain('else if (status_Left_ToF == 3) dist_Left_ToF = 0.0;');
    expect(code).toContain('else dist_Left_ToF = 800.0;');
    expect(code).toContain('float sig_Left_ToF = constrain((1.0 - dist_Left_ToF / 800.0) * 100.0, 0.0, 100.0);');
    // Second sensor uses the default 500 mm full-scale.
    expect(code).toContain('static float dist_Right_ToF = 500.0;');
  });

  it('emits the ToF address trick before the TCS34725 init and inverts far = high', () => {
    const nodes: DiagramNode[] = [
      makeSensor({ id: 'tof-1', type: 'sensor-tof', label: 'Front ToF', arduinoPort: undefined, xshutPin: '4', invert: true }),
      makeSensor({ id: 'color-1', type: 'sensor-color', label: 'Front Color', arduinoPort: undefined }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'tof-1', to: 'motor-left', weight: 1 }),
      { ...conn({ id: 'c2', from: 'color-1', to: 'motor-right', weight: 1 }), fromPort: 'red' },
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    // ToF sensors must be readdressed off 0x29/0x52 before the TCS34725 (fixed
    // at 0x29) is configured, so the shared bus is unambiguous.
    expect(code.indexOf('tof_Front_ToF.InitSensor(0x54);')).toBeLessThan(
      code.indexOf('tcs34725_begin(0x02);'),
    );
    // Invert → far reads higher.
    expect(code).toContain('float sig_Front_ToF = constrain((dist_Front_ToF / 500.0) * 100.0, 0.0, 100.0);');
  });

  it('maps the configured color-sensor gain to the CONTROL register', () => {
    const nodes: DiagramNode[] = [
      makeSensor({ id: 'color-1', type: 'sensor-color', label: 'Front Color', arduinoPort: undefined, colorGain: 60 }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      { ...conn({ id: 'c1', from: 'color-1', to: 'motor-left', weight: 1 }), fromPort: 'red' },
      { ...conn({ id: 'c2', from: 'color-1', to: 'motor-right', weight: 1 }), fromPort: 'red' },
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    // 60x → CONTROL register 0x03.
    expect(code).toContain('tcs34725_begin(0x03);');
  });

  it('falls back to a declared channel when fromPort is unknown', () => {
    const nodes: DiagramNode[] = [
      makeSensor({
        id: 'color-1',
        type: 'sensor-color',
        label: 'Front Color',
        arduinoPort: undefined,
      }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      // `fromPort: 'ultraviolet'` — never declared. Force a raw cast to
      // simulate a persisted diagram authored against an older schema.
      {
        ...conn({ id: 'c1', from: 'color-1', to: 'motor-left', weight: 1 }),
        fromPort: 'ultraviolet' as unknown as 'clear',
      },
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // Emitter must not reference sig_Front_Color_ultraviolet (never declared).
    expect(code).not.toContain('sig_Front_Color_ultraviolet');
    // And must fall back to a variable that *is* declared — clear is first.
    expect(code).toContain('input_Left_Wheel += sig_Front_Color_clear * 1.0000;');
  });

  it('checks Wire.endTransmission and requestFrom in tcs34725_read_all', () => {
    const nodes: DiagramNode[] = [
      makeSensor({
        id: 'color-1',
        type: 'sensor-color',
        label: 'Front Color',
        arduinoPort: undefined,
      }),
      makeMotor(),
      makeRightMotor(),
    ];
    const connections: DiagramConnection[] = [
      { ...conn({ id: 'c1', from: 'color-1', to: 'motor-left', weight: 1 }), fromPort: 'red' },
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    // Driver must bail out on I2C error — endTransmission != 0 returns a zero sample.
    expect(code).toContain('if (Wire.endTransmission() != 0) {');
    // Single 8-byte read covers all four channels via auto-increment.
    expect(code).toContain('Wire.write(0xA0 | 0x14);');
    expect(code).toContain('uint8_t bytesRead = Wire.requestFrom(TCS34725_ADDR, (uint8_t)8);');
    expect(code).toContain('if (bytesRead != 8) {');
  });

  it('emits TM1637 display include, declaration, brightness, and showNumberDec', () => {
    const nodes: DiagramNode[] = [
      makeSensor(),
      {
        id: 'disp-1',
        type: 'display-tm1637',
        label: 'Readout',
        x: 0,
        y: 0,
        clkPin: '2',
        gpioPin: '3',
        brightness: 5,
      },
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'disp-1', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('#include <TM1637Display.h>');
    expect(code).toContain('const int TM1637_Readout_CLK = 2;');
    expect(code).toContain('const int TM1637_Readout_GPIO = 3;');
    expect(code).toContain('TM1637Display display_Readout(TM1637_Readout_CLK, TM1637_Readout_GPIO);');
    expect(code).toContain('display_Readout.setBrightness(5);');
    expect(code).toContain('display_Readout.clear();');
    // Aggregated input rounded and clamped to 4-digit display range.
    expect(code).toContain('int value_Readout = constrain((int)lround(input_Readout), -999, 9999);');
    expect(code).toContain('display_Readout.showNumberDec(value_Readout, false);');
    // Servo.h should not appear when the only actuator is the display.
    expect(code).not.toContain('#include <Servo.h>');
  });

  it('generates oscillator node with sin(2*PI*f*t) form', () => {
    const osc: DiagramNode = {
      id: 'osc-1',
      type: 'compute-oscillator',
      label: 'Wobble',
      x: 0,
      y: 0,
      frequencyHz: 2.5,
      amplitude: 80,
    };
    const nodes: DiagramNode[] = [osc, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'osc-1', to: 'motor-left', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('float sig_Wobble = 80.0000 * sin(2.0 * PI * 2.5000 * (millis() / 1000.0));');
  });

  it('generates oscillator with default amplitude=100 and freq=1Hz', () => {
    const osc: DiagramNode = {
      id: 'osc-1',
      type: 'compute-oscillator',
      label: 'Default',
      x: 0,
      y: 0,
    };
    const nodes: DiagramNode[] = [osc, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'osc-1', to: 'motor-left', weight: 1 }),
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    expect(code).toContain('100.0000 * sin(2.0 * PI * 1.0000');
  });

  it('generates noise node with scaled random(-10000, 10001) form', () => {
    const noise: DiagramNode = {
      id: 'noise-1',
      type: 'compute-noise',
      label: 'Jitter',
      x: 0,
      y: 0,
      amplitude: 30,
    };
    const nodes: DiagramNode[] = [noise, makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'noise-1', to: 'motor-left', weight: 1 }),
    ];
    const code = generateSketch(buildGraph(nodes, connections));

    expect(code).toContain('float sig_Jitter = 30.0000 * ((float)random(-10000, 10001) / 10000.0);');
  });

  it('generates noise with default amplitude=50', () => {
    const noise: DiagramNode = {
      id: 'noise-1',
      type: 'compute-noise',
      label: 'Default',
      x: 0,
      y: 0,
    };
    const code = generateSketch(
      buildGraph([noise, makeMotor()], [
        conn({ id: 'c1', from: 'noise-1', to: 'motor-left', weight: 1 }),
      ]),
    );

    expect(code).toContain('50.0000 * ((float)random');
  });

  it('clamps loopPeriodMs to safe bounds', () => {
    const nodes: DiagramNode[] = [makeSensor(), makeMotor()];
    const connections: DiagramConnection[] = [
      conn({ id: 'c1', from: 'sensor-1', to: 'motor-left', weight: 1 }),
    ];
    // Zero would yield Infinity delay-buffer sizes; the clamp must keep it ≥ 1.
    const graph = buildGraph(nodes, connections, 0);
    expect(graph.loopPeriodMs).toBeGreaterThanOrEqual(1);
    expect(generateSketch(graph)).toContain('if (_elapsed < 1) delay(1 - _elapsed);');

    // Absurdly large values must be clamped, not propagated.
    const bigGraph = buildGraph(nodes, connections, 100000);
    expect(bigGraph.loopPeriodMs).toBeLessThanOrEqual(1000);
  });

  it('expands compound instances before codegen', () => {
    const passthrough: CompoundTypeDefinition = {
      id: 'gain',
      displayName: 'Gain',
      body: {
        nodes: [
          { id: 'in', type: 'compound-input', label: 'in', x: 0, y: 0 },
          { id: 'sum', type: 'compute-summation', label: 'InnerSum', x: 0, y: 0 },
          { id: 'out', type: 'compound-output', label: 'out', x: 0, y: 0 },
        ],
        connections: [
          conn({ id: 'b1', from: 'in', to: 'sum', weight: 1 }),
          conn({ id: 'b2', from: 'sum', to: 'out', weight: 0.5 }),
        ],
      },
    };
    const nodes: DiagramNode[] = [
      makeSensor(),
      {
        id: 'inst-1', type: 'compound', compoundTypeId: 'gain',
        label: 'Gain', x: 0, y: 0,
      },
      makeMotor(),
    ];
    const connections: DiagramConnection[] = [
      conn({ id: 'e1', from: 'sensor-1', to: 'inst-1', toPort: 'in', weight: 1 }),
      conn({ id: 'e2', from: 'inst-1', to: 'motor-left', fromPort: 'out', weight: 1 }),
    ];
    const graph = buildGraph(nodes, connections, 20, [passthrough]);
    const code = generateSketch(graph);

    // The compound instance's inner summation node appears with the
    // instance-prefixed label.
    expect(code).toContain('sig_InnerSum');
    // The port anchors became summation pass-throughs with their own
    // sig_<label> variables.
    expect(code).toContain('sig_in');
    expect(code).toContain('sig_out');
    // The outer sensor's value reaches the inner sum through the
    // pass-through input anchor.
    expect(code).toContain('input_in += sig_Sensor_1');
    // The 0.5 weight on the inner b2 edge is preserved.
    expect(code).toContain('* 0.5000');
    // No compound or port-anchor symbols leak into the sketch.
    expect(code).not.toContain('compound');
  });

  it('generates non-linear transfer function', () => {
    const nodes: DiagramNode[] = [makeSensor(), makeMotor()];
    const connections: DiagramConnection[] = [
      conn({
        id: 'c1',
        from: 'sensor-1',
        to: 'motor-left',
        weight: 1,
        transferMode: 'nonlinear',
        transferPoints: [
          { x: 0, y: 0 },
          { x: 0.5, y: 0.8 },
          { x: 1, y: 1 },
        ],
      }),
    ];
    const graph = buildGraph(nodes, connections);
    const code = generateSketch(graph);

    expect(code).toContain('float transfer_');
    expect(code).toContain('float x)');
    expect(code).toContain('transfer_Sensor_1_Left_Wheel_0');
    // No * 1023.0 scaling — output is already in -100 to 100 signal domain
    expect(code).not.toContain('* 1023.0');
  });
});
